merge(BE): Merge backend-features hiện tại với nhánh test, đồng thời viết thêm test tính năng track login streak và thêm docstring cho các fixtures.

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -27,14 +27,14 @@ services:
     environment:
       POSTGRES_URL: postgresql+asyncpg://postgres:Q6L0N2H0LQS5016SQL5888@db:5432/group_project_sample
       POSTGRES_URL_TEST: postgresql+asyncpg://postgres:Q6L0N2H0LQS5016SQL5888@db:5432/group_project_sample
-      OLLAMA_HOST: http://ollama:11434
+      # OLLAMA_HOST: http://ollama:11434
     depends_on:
       db:
         condition: service_healthy
-      ollama:
-        condition: service_started
-      ollama-init:
-        condition: service_completed_successfully
+      # ollama:
+      #   condition: service_started
+      # ollama-init:
+      #   condition: service_completed_successfully
     volumes:
       - ./backend:/code/backend
     command:
@@ -54,46 +54,46 @@ services:
         '0.0.0.0',
       ]
 
-  ollama:
-    image: ollama/ollama
-    ports:
-      - '11434:11434'
-    volumes:
-      - ollama_data:/root/.ollama
-    deploy:
-      resources:
-        reservations:
-          devices:
-            - driver: nvidia
-              count: 1
-              capabilities: [gpu]
+  # ollama:
+  #   image: ollama/ollama
+  #   ports:
+  #     - '11434:11434'
+  #   volumes:
+  #     - ollama_data:/root/.ollama
+  #   # deploy:
+  #   #   resources:
+  #   #     reservations:
+  #   #       devices:
+  #   #         - driver: nvidia
+  #   #           count: 1
+  #   #           capabilities: [gpu]
 
-  ollama-init:
-    image: ollama/ollama
-    depends_on:
-      - ollama
-    environment:
-      - OLLAMA_HOST=http://ollama:11434
-    entrypoint: ['/bin/sh']
-    command:
-      - '-c'
-      - |
-        echo "Waiting for Ollama server to be active..."
-        while ! ollama list > /dev/null 2>&1; do sleep 1; done
+  # ollama-init:
+  #   image: ollama/ollama
+  #   depends_on:
+  #     - ollama
+  #   environment:
+  #     - OLLAMA_HOST=http://ollama:11434
+  #   entrypoint: ['/bin/sh']
+  #   command:
+  #     - '-c'
+  #     - |
+  #       echo "Waiting for Ollama server to be active..."
+  #       while ! ollama list > /dev/null 2>&1; do sleep 1; done
 
-        echo "Server active. Starting model pulls..."
+  #       echo "Server active. Starting model pulls..."
 
-        echo "Pulling nomic-embed-text..."
-        until ollama pull nomic-embed-text; do echo "Network drop. Retrying nomic..."; sleep 2; done
+  #       echo "Pulling nomic-embed-text..."
+  #       until ollama pull nomic-embed-text; do echo "Network drop. Retrying nomic..."; sleep 2; done
 
-        echo "Pulling llama3.1..."
-        until ollama pull llama3.1; do echo "Network drop. Retrying llama3.1..."; sleep 2; done
+  #       echo "Pulling llama3.1..."
+  #       until ollama pull llama3.1; do echo "Network drop. Retrying llama3.1..."; sleep 2; done
 
-        echo "Pulling llama3.2-vision..."
-        until ollama pull llama3.2-vision; do echo "Network drop. Retrying vision..."; sleep 2; done
+  #       echo "Pulling llama3.2-vision..."
+  #       until ollama pull llama3.2-vision; do echo "Network drop. Retrying vision..."; sleep 2; done
 
-        echo "All models pulled successfully! Exiting init container."
+  #       echo "All models pulled successfully! Exiting init container."
 
 volumes:
   postgres_data:
-  ollama_data:
+  # ollama_data:
